---
title: "Mini Project 2"
author: "Talmage Hilton, Gavin Hatch, Ty Hawkes"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
fontsize: 11pt
geometry: margin=1in
header-includes:
- \usepackage{setspace}
- \singlespacing
---

# Intro

-   Motivation, why \# Data Generation

-   Description of data generation process \# Simulation Design

-   Description of simulation design

-   Tests used (F and LRT) \# Results

-   Summary tables and figures

-   

    ## for large n

    ------------- compound - random - autoregres -

-   type1 LRT -

-   type1 F -

-   power LRT -

-   power F -

-   

    ## for small n

    ------------- compound - random - autoregres -

-   type1 LRT -

-   type1 F -

-   power LRT -

-   power F -

$$
\Sigma = 
\begin{pmatrix}
\sigma_0^2 & \sigma_{01} \\
\sigma_{01} & \sigma_1^2
\end{pmatrix}
$$

$$
\text{Cov}(Y_i) = Z_i 
\begin{pmatrix}
\sigma_0^2 & \sigma_{01} \\
\sigma_{01} & \sigma_1^2
\end{pmatrix}
Z_i' + \sigma^2 I
$$

where 
$$
Z_i = 
\begin{pmatrix}
1 & t_{i1} \\
1 & t_{i2} \\
\vdots & \vdots \\
1 & t_{in_i}
\end{pmatrix},
\quad
\text{so that}
\quad
\text{Cov}(Y_i) =
\begin{pmatrix}
\sigma_0^2 + 2t_{i1}\sigma_{01} + t_{i1}^2\sigma_1^2 & \cdots \\
\vdots & \ddots
\end{pmatrix}
$$

$V = \sigma_b^2 1 1' + \sigma_c^2 x x' + \sigma_e^2 I$.

AR(1): $(V)_{ij} = \sigma^2\rho^{|i-j|}$.

Compute the Cholesky factorization
$V = C C'$,
where $C$ is lower-triangular.

Generate independent standard normal vectors
$z_i \sim N(0,I_5)$ for each subject.

Induce correlation:
$y_i = X_i\beta + C z_i$,
which ensures $\text{Var}(y_i) = C \text{Var}(z_i) C' = C I C' = V$.

$$
\operatorname{Cov}(Y_{ij}, Y_{ik}) = \rho \sigma^2, \quad \forall i \neq k
$$

$$
Y_{ij} = \beta_0 + \beta_1 \, \text{time}_{ij} \times \text{treatment}_i + \epsilon_{ij},
$$

where 

$$
{\epsilon}_i = 
\begin{pmatrix}
\epsilon_{i1} \\
\epsilon_{i2} \\
\vdots \\
\epsilon_{in_i}
\end{pmatrix}
\sim N(\mathbf{0}, V),
$$

and \( V \) represents one of the three covariance structures defined above (Compound Symmetric, Random Coefficients, or Autoregressive). 

Each subject’s repeated measures are thus correlated according to \( V \), while treatment effects are introduced through the fixed effects \( \beta_0 \) and \( \beta_1 \).

